<a href="https://colab.research.google.com/github/sdw1621/python_exercise/blob/main/%EC%98%88%EC%A0%9C_%EC%A4%91%EC%8B%AC_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%9E%85%EB%AC%B8_CH11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**11-1 CSV 파일 읽기**

In [1]:
import csv

f = open('month_temp.csv','r',encoding='UTF-8')
lines = csv.reader(f)
for line in lines:
  print(line)
f.close()

['지점', '일시', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)']
['119', '2019-10-01', '22', '15.7', '27.4']
['119', '2019-10-02', '21.9', '20.4', '23.8']
['119', '2019-10-03', '22.8', '19.9', '27.8']
['119', '2019-10-04', '21.9', '17.8', '26.9']
['119', '2019-10-05', '18.9', '15.7', '22']
['119', '2019-10-06', '18', '14', '22']
['119', '2019-10-07', '14.8', '13.4', '17.9']
['119', '2019-10-08', '15', '10.7', '20.6']
['119', '2019-10-09', '12.8', '6.4', '19.6']
['119', '2019-10-10', '14.9', '9.5', '20.2']
['119', '2019-10-11', '18.8', '12.1', '24.8']
['119', '2019-10-12', '18.3', '14.1', '23.3']
['119', '2019-10-13', '16.9', '12.5', '22.9']
['119', '2019-10-14', '14', '8.5', '19.4']
['119', '2019-10-15', '13.3', '7.3', '19.6']
['119', '2019-10-16', '13.9', '7.9', '20']
['119', '2019-10-17', '14.6', '9.1', '20.6']
['119', '2019-10-18', '16.7', '10', '21.9']
['119', '2019-10-19', '16', '10.4', '22.2']
['119', '2019-10-20', '15.1', '10.8', '21.7']
['119', '2019-10-21', '16.1', '9.5', '23.9']
['119', '2019-10-22', '16.6', '11.1', '23']
['119', '2019-10-23', '17', '12.4', '20']
['119', '2019-10-24', '18.6', '14.1', '23.3']
['119', '2019-10-25', '16.6', '10.7', '21.7']
['119', '2019-10-26', '9.8', '6.4', '13.9']
['119', '2019-10-27', '10.2', '3', '16.8']
['119', '2019-10-28', '12.4', '6.3', '17.4']
['119', '2019-10-29', '12.6', '8.2', '18.1']
['119', '2019-10-30', '10.3', '3.3', '17.1']
['119', '2019-10-31', '14.1', '7.3', '20.4']

###**11-2 CSV 파일 데이터 하나씩 출력하기**

In [3]:
import csv

f = open('month_temp.csv','r',encoding='utf-8')
lines = csv.reader(f)
for line in lines:
  for x in range(len(line)):
    print(line[x])
f.close()

지점
일시
평균기온(°C)
최저기온(°C)
최고기온(°C)
119
2019-10-01
22
15.7
27.4
119
2019-10-02
21.9
20.4
23.8
119
2019-10-03
22.8
19.9
27.8
119
2019-10-04
21.9
17.8
26.9
119
2019-10-05
18.9
15.7
22
119
2019-10-06
18
14
22
119
2019-10-07
14.8
13.4
17.9
119
2019-10-08
15
10.7
20.6
119
2019-10-09
12.8
6.4
19.6
119
2019-10-10
14.9
9.5
20.2
119
2019-10-11
18.8
12.1
24.8
119
2019-10-12
18.3
14.1
23.3
119
2019-10-13
16.9
12.5
22.9
119
2019-10-14
14
8.5
19.4
119
2019-10-15
13.3
7.3
19.6
119
2019-10-16
13.9
7.9
20
119
2019-10-17
14.6
9.1
20.6
119
2019-10-18
16.7
10
21.9
119
2019-10-19
16
10.4
22.2
119
2019-10-20
15.1
10.8
21.7
119
2019-10-21
16.1
9.5
23.9
119
2019-10-22
16.6
11.1
23
119
2019-10-23
17
12.4
20
119
2019-10-24
18.6
14.1
23.3
119
2019-10-25
16.6
10.7
21.7
119
2019-10-26
9.8
6.4
13.9
119
2019-10-27
10.2
3
16.8
119
2019-10-28
12.4
6.3
17.4
119
2019-10-29
12.6
8.2
18.1
119
2019-10-30
10.3
3.3
17.1
119
2019-10-31
14.1
7.3
20.4

###**11-3 특정 일자 기온 데이터 출력하기**

In [4]:
import csv

f = open('month_temp.csv','r',encoding='utf-8')
lines = csv.reader(f)
for line in lines:
  if '2019-10-20' in line:
    print(line)
f.close()

['119', '2019-10-20', '15.1', '10.8', '21.7']

###**11-4 CSV 파일의 헤더 추출**

In [5]:
import csv

f = open('month_temp.csv', 'r', encoding='utf-8')
lines = csv.reader(f)
header = next(lines)

print(header)

f.close()

['지점', '일시', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)']

###**11-5 CSV 일교차 구하기**

In [7]:
import csv

f = open('month_temp.csv','r',encoding='utf-8')
lines = csv.reader(f)

print('%s %s %s %s' %('일자','최저기온', '최고기온', '일교차'))

next(lines)
for line in lines:
  diff = float(line[4]) - float(line[3])
  print('%s %.1f %.1f %.1f' %(line[1], float(line[3]), float(line[4]), diff))

f.close()

일자 최저기온 최고기온 일교차
2019-10-01 15.7 27.4 11.7
2019-10-02 20.4 23.8 3.4
2019-10-03 19.9 27.8 7.9
2019-10-04 17.8 26.9 9.1
2019-10-05 15.7 22.0 6.3
2019-10-06 14.0 22.0 8.0
2019-10-07 13.4 17.9 4.5
2019-10-08 10.7 20.6 9.9
2019-10-09 6.4 19.6 13.2
2019-10-10 9.5 20.2 10.7
2019-10-11 12.1 24.8 12.7
2019-10-12 14.1 23.3 9.2
2019-10-13 12.5 22.9 10.4
2019-10-14 8.5 19.4 10.9
2019-10-15 7.3 19.6 12.3
2019-10-16 7.9 20.0 12.1
2019-10-17 9.1 20.6 11.5
2019-10-18 10.0 21.9 11.9
2019-10-19 10.4 22.2 11.8
2019-10-20 10.8 21.7 10.9
2019-10-21 9.5 23.9 14.4
2019-10-22 11.1 23.0 11.9
2019-10-23 12.4 20.0 7.6
2019-10-24 14.1 23.3 9.2
2019-10-25 10.7 21.7 11.0
2019-10-26 6.4 13.9 7.5
2019-10-27 3.0 16.8 13.8
2019-10-28 6.3 17.4 11.1
2019-10-29 8.2 18.1 9.9
2019-10-30 3.3 17.1 13.8
2019-10-31 7.3 20.4 13.1

###**11-6 CSV 파일 쓰기**

In [9]:
import csv

file1 = open('month_temp.csv','r',encoding='utf-8')
file2 = open('month_temp2.csv','w',encoding='utf-8',newline='')
lines = csv.reader(file1)
wr = csv.writer(file2)

wr.writerow(['일자','최저기온','최고기온','일교차'])
next(lines)
for line in lines:
  diff = float(line[4]) - float(line[3])
  diff = format(diff, '.1f')
  wr.writerow([line[1], float(line[3]), float(line[4]), diff])

print('파일 쓰기 완료!')
file1.close()
file2.close()

파일 쓰기 완료!

###**Q11-1 코딩 연습 : 데이터 사이에 '/' 삽입하기**

In [11]:
import csv

f = open('month_temp.csv', 'r', encoding='utf-8')
lines = csv.reader(f)
for line in lines:
  for x in line:
    print('%s' %x, end='/')
  print()
f.close()

지점/일시/평균기온(°C)/최저기온(°C)/최고기온(°C)/
119/2019-10-01/22/15.7/27.4/
119/2019-10-02/21.9/20.4/23.8/
119/2019-10-03/22.8/19.9/27.8/
119/2019-10-04/21.9/17.8/26.9/
119/2019-10-05/18.9/15.7/22/
119/2019-10-06/18/14/22/
119/2019-10-07/14.8/13.4/17.9/
119/2019-10-08/15/10.7/20.6/
119/2019-10-09/12.8/6.4/19.6/
119/2019-10-10/14.9/9.5/20.2/
119/2019-10-11/18.8/12.1/24.8/
119/2019-10-12/18.3/14.1/23.3/
119/2019-10-13/16.9/12.5/22.9/
119/2019-10-14/14/8.5/19.4/
119/2019-10-15/13.3/7.3/19.6/
119/2019-10-16/13.9/7.9/20/
119/2019-10-17/14.6/9.1/20.6/
119/2019-10-18/16.7/10/21.9/
119/2019-10-19/16/10.4/22.2/
119/2019-10-20/15.1/10.8/21.7/
119/2019-10-21/16.1/9.5/23.9/
119/2019-10-22/16.6/11.1/23/
119/2019-10-23/17/12.4/20/
119/2019-10-24/18.6/14.1/23.3/
119/2019-10-25/16.6/10.7/21.7/
119/2019-10-26/9.8/6.4/13.9/
119/2019-10-27/10.2/3/16.8/
119/2019-10-28/12.4/6.3/17.4/
119/2019-10-29/12.6/8.2/18.1/
119/2019-10-30/10.3/3.3/17.1/
119/2019-10-31/14.1/7.3/20.4/

###**Q11-2 코딩 연습 : 10일간 평균 기온 구하기**

In [12]:
import csv

f = open('month_temp.csv','r',encoding='utf-8')
lines = csv.reader(f)

# 헤더를 건너뛴다.
next(lines)

sum = 0
for line in lines:
  if(int(line[1][-2:]) <= 10):
    sum += float(line[2])

avg = sum/10
print("10일간 평균 기온 : %.1f" %avg)

f.close()

10일간 평균 기온 : 18.3

###**예제11-7 '경주시'의 '신대원약국' 주소 출력**

In [13]:
import csv

f = open('pharm_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

for line in lines:
  if line[1] == '경주시' and line[0] == '신대원약국':
    print(line[0], line[1], line[2], sep='/')

f.close()

신대원약국/경주시/경상북도 경주시 화랑로 53 (성건동)

###**예제11-8 '수지'의 '로얄스포츠' 건물의 약국**

In [14]:
import csv

f = open('pharm_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

for line in lines:
  if ('수지' in line[2]) and ('로얄스포츠' in line[2]):
    print(line[2], line[0], line[3], sep='/')

f.close()

경기도 용인시 수지구 풍덕천로 119 118호 (풍덕천동, 로얄스포츠센터)/희망약국/20170216
경기도 용인시 수지구 풍덕천로 119 119호 (풍덕천동, 로얄스포츠센터)/로얄약국/20170717
경기도 용인시 수지구 풍덕천로 119 305호 (풍덕천동, 로얄스포츠센터)/이화옵티마약국/20170314
경기도 용인시 수지구 풍덕천로 119 208호 (풍덕천동, 로얄스포츠센터)/수지윤약국/20170103

###**예제11-9 최근 5년 이내 개설된 약국 수**

In [15]:
import csv

f = open('pharm_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

city = '원주시'
count = 0
recent = 0
for line in lines:
  if line[1] == city:
    count += 1
    if int(line[3]) > 20140901:
      recent += 1

print('%s의 약국 수 : %d개' %(city, count))
print('5년 이내 개설된 약국 수 : %d개' %recent)

원주시의 약국 수 : 156개
5년 이내 개설된 약국 수 : 55개

###**예제11-10 경상북도 2010년에 개설한 약국 목록**

In [16]:
import csv

f = open('pharm_2019.csv','r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)
print('번호', header[1], header[0], header[4], header[5], sep=',')

number = 1
for line in lines:
  if ('경상북도' in line[2]) and (int(line[3]) >= 20100101 and int(line[3]) <= 20101231):
    print(number, '.', sep='', end='')
    print(line[1], line[0], line[4], line[5], sep='/')
    number += 1

f.close()

번호,지역,약국명,경도,위도
1.포항북구/영천온누리약국/129.3836663/36.0824353
2.포항북구/늘사랑약국/129.3754548/36.0597963
3.구미시/형곡비타민약국/128.3398692/36.1143363
4.영덕군/열린약국/129.4431662/36.5071346
5.포항북구/아이원약국/129.4023367/36.0848535
6.울진군/죽변약국/129.4208251/37.0604868
7.청송군/진보약국/129.0443496/36.5287978
8.경산시/옥곡수약국/128.7326142/35.8130067
9.성주군/제일약국/128.2869221/35.9177670
10.구미시/프라자약국/128.3637496/36.1027545
11.성주군/다솜약국/128.2864250/35.9188010
12.포항남구/미소약국/129.4032875/35.9632263
13.포항남구/희약국/129.3395994/36.0059557
14.영천시/장수약국/128.9447775/35.9763708
15.김천시/이화온누리약국/128.1274441/36.1219157
16.안동시/푸른약국/128.7243383/36.5635810
17.경주시/대안약국/129.2223235/35.9909424
18.포항남구/은혜약국/129.3152376/36.0048282
19.예천군/건강약국/128.3872618/36.5445614
20.구미시/정우약국/128.4302803/36.0960469
21.구미시/새보령약국/128.4224091/36.0952758
22.김천시/건강한마을약국/128.2598176/36.1590220
23.구미시/대학약국/128.3829163/36.1018072
24.안동시/장춘당약국/128.7298160/36.5654449
25.구미시/희망약국/128.3380932/36.1291413
26.안동시/용상약국/128.7512913/36.5589970
27.경산시/청솔약국/128.8234867/35.8197835
28.상주시/상주종합약국/128.1596065/36.4145342
29.구미시/옥계하나약국/128.4218021/36.1380448
30.고령군/민다약국/128.2671006/35.7291887
31.포항북구/제일온누리약국/129.3727116/36.0690666
32.경주시/수약국/129.2226839/35.9912753
33.구미시/미르약국/128.3357641/36.1105070
34.포항남구/한미약국/129.5537888/35.9904281
35.경산시/백천동방약국/128.7388851/35.8040407
36.경산시/동방약국/128.7529217/35.8172074

###**예제11-11 용인 수지구 약국을 가나다순 정렬**

In [20]:
import csv

f = open('pharm_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)
print('번호', header[0], header[2], sep=',')

data = []

for line in lines:
  if line[1] == '용인수지구':
    tmp = '%s/%s' %(line[0], line[2])
    data.append(tmp)

data.sort()

number = 1
for x in data:
  print('%d. %s' %(number, x))
  number += 1

f.close()

번호,약국명,주소
1. 5층우리약국/경기도 용인시 수지구 풍덕천로 149 501호 (풍덕천동, 현대그린프라자)
2. LG(엘지)약국/경기도 용인시 수지구 성복2로 84 105호 (성복동, 엘지빌리지1차상가)
3. 가람약국/경기도 용인시 수지구 만현로 88 (상현동, 상현종합상가201-2호)
4. 광교 기분좋은 약국/경기도 용인시 수지구 광교마을로 54 에스비타운 110호 (상현동)
5. 광교수약국/경기도 용인시 수지구 광교중앙로 320 (상현동)
6. 광교약국/경기도 용인시 수지구 광교중앙로 316 102호 (상현동, 광교시티하임)
7. 광교윤하약국/경기도 용인시 수지구 광교중앙로 314 104호 (상현동, 세현빌딩 )
8. 광교팜약국/경기도 용인시 수지구 광교중앙로 304 105호 (상현동)
9. 광교푸른약국/경기도 용인시 수지구 광교중앙로 308 305호 (상현동)
10. 그린약국/경기도 용인시 수지구 성복2로76번길 26-6 (성복동,신봉V샤르망102호)
11. 기린약국/경기도 용인시 수지구 성복2로 108-2 (성복동,웰스톤갤러리B109~B110호)
12. 나무약국/경기도 용인시 수지구 수지로342번길 11 304호 (풍덕천동)
13. 다사랑약국/경기도 용인시 수지구 만현로 103 106호 (상현동, 한길프라자)
14. 다솜약국/경기도 용인시 수지구 정평로 43 102호 (풍덕천동, 우성상가)
15. 다온약국/경기도 용인시 수지구 광교중앙로 294 108호 (상현동)
16. 단비약국/경기도 용인시 수지구 문정로 15 (풍덕천동,평은프라자 1층)
17. 대학당약국/경기도 용인시 수지구 수지로342번길 27 106호 (풍덕천동, 동보아파트상가)
18. 대학약국/경기도 용인시 수지구 죽전로 152-1 103호 (죽전동, 단대프라자I )
19. 데이파크약국/경기도 용인시 수지구 성복2로 51 (성복동, 데이파크B동 120호)
20. 동성약국/경기도 용인시 수지구 용구대로 2736 1층 (죽전동, 영일죽전빌딩)
21. 동천약국/경기도 용인시 수지구 손곡로 83 동천타워 1동 108호 (동천동)
22. 라임약국/경기도 용인시 수지구 신봉2로 73 태천빌딩2 101호 (신봉동)
23. 로얄약국/경기도 용인시 수지구 풍덕천로 119 119호 (풍덕천동, 로얄스포츠센터)
24. 맑은샘약국/경기도 용인시 수지구 신봉2로 3 (신봉동,홍천말프라자 302)
25. 맑은생한약국/경기도 용인시 수지구 수지로342번길 16 112호 (풍덕천동)
26. 매일봄약국/경기도 용인시 수지구 수풍로 107 104호 (동천동)
27. 메디칼약국/경기도 용인시 수지구 풍덕천로 114 강동빌딩 101,102호 (풍덕천동)
28. 메디플러스약국/경기도 용인시 수지구 풍덕천로129번길 9 101호 (풍덕천동, 오성빌딩 )
29. 모범약국/경기도 용인시 수지구 수지로 203 E 마트 지하1층 (신봉동)
30. 미래약국/경기도 용인시 수지구 만현로 110 A-407호 (상현동, 원희캐슬프라자)
31. 미소약국/경기도 용인시 수지구 문정로 22 (풍덕천동)
32. 바른생각약국/경기도 용인시 수지구 포은대로313번길 7-14 수정빌딩 1층 (풍덕천동)
33. 바른약국/경기도 용인시 수지구 동천로 83 104호 (동천동, 윤창빌딩)
34. 밝은약국/경기도 용인시 수지구 광교중앙로 320 503호 (상현동)
35. 베델약국/경기도 용인시 수지구 문인로 59 107호 (풍덕천동, 삼익상가)
36. 보은약국/경기도 용인시 수지구 정평로 40-1 302호 (풍덕천동, 거묵상가)
37. 봄빛약국/경기도 용인시 수지구 풍덕천로 91 103호 (풍덕천동, 주공1단지아파트)
38. 비전약국/경기도 용인시 수지구 문정로 13 103호 (풍덕천동, 중수프라자)
39. 삼성메디칼약국/경기도 용인시 수지구 진산로 106 (풍덕천동, 훼미리빌딩1층)
40. 상현메디칼약국/경기도 용인시 수지구 만현로 100 203호 (상현동, 거묵프라자)
41. 새모범약국/경기도 용인시 수지구 포은대로 552 (죽전동, 죽전이마트 1층)
42. 새보건약국/경기도 용인시 수지구 풍덕천로130번길 4 1층 (풍덕천동)
43. 샘물약국/경기도 용인시 수지구 문정로 46 305호 (풍덕천동, 한길타운)
44. 서울약국/경기도 용인시 수지구 수지로 124 성복스퀘어/근린생활시설 107호 (성복동)
45. 서원약국/경기도 용인시 수지구 상현로 34 102호 (상현동, 성진)
46. 성복약국/경기도 용인시 수지구 심곡로 87 (성복동, 33-5 아이조움빌딩B205)
47. 성복역 우리약국/경기도 용인시 수지구 수지로112번길 11 107호 (성복동)
48. 성복온누리약국/경기도 용인시 수지구 성복2로 49 1층 (성복동)
49. 세종옵티마약국/경기도 용인시 수지구 수지로 62 (상현동)
50. 센트럴약국/경기도 용인시 수지구 신봉2로 2 114호 (신봉동, 센트럴쇼핑몰)
51. 솔약국/경기도 용인시 수지구 만현로 113 106호 (상현동, 미래프라자)
52. 수빈약국/경기도 용인시 수지구 대지로 58 나동 309호 (죽전동, 선진포리스트)
53. 수약국/경기도 용인시 수지구 만현로 82-4 헤르메스상가 404-1호 (상현동)
54. 수지드림약국/경기도 용인시 수지구 손곡로 95 110~111호 (동천동, 송란아트프라자)
55. 수지메디칼약국/경기도 용인시 수지구 동천로 36 (동천동,영재빌딩105호)
56. 수지민들레 한약국/경기도 용인시 수지구 풍덕천로 144 503호 (풍덕천동, 현대그린프라자)
57. 수지성서약국/경기도 용인시 수지구 성복2로 230 106호 (성복동)
58. 수지썬프라자약국/경기도 용인시 수지구 풍덕천로 127 (풍덕천동,수지프라자 101호)
59. 수지우리약국/경기도 용인시 수지구 성복2로 126 (성복동, 수지LG빌리지3차상가 118호)
60. 수지윤약국/경기도 용인시 수지구 풍덕천로 119 208호 (풍덕천동, 로얄스포츠센터)
61. 수지정다운약국/경기도 용인시 수지구 신봉2로 2 217호 (신봉동, 센트럴500)
62. 수지한림약국/경기도 용인시 수지구 문정로 32 1층 (풍덕천동)
63. 수지햇살약국/경기도 용인시 수지구 광교중앙로 316 (상현동, 킴앤코시티하임1 303-1)
64. 수지행복한약국/경기도 용인시 수지구 진산로 100 105호 (풍덕천동, 골드라인빌딩 제상가동)
65. 숨약국/경기도 용인시 수지구 푸른솔로 87 108호 (죽전동, 그랜드프라자)
66. 아이맘약국/경기도 용인시 수지구 현암로 154 2층 205호 (죽전동, 거풍프라자)
67. 안데르센약국/경기도 용인시 수지구 정평로 40-1 403호 (풍덕천동)
68. 앞서가는21세기약국/경기도 용인시 수지구 대지로 20 101호 (죽전동, 죽전빌딩)
69. 연두약국/경기도 용인시 수지구 신봉1로 165 (신봉동, 동광프라자 203호)
70. 연수우리들약국/경기도 용인시 수지구 용구대로2771번길 66 106-3호 (죽전동)
71. 열린온누리약국/경기도 용인시 수지구 대지로 43 107호 (죽전동, 금강프라자)
72. 열린우리약국/경기도 용인시 수지구 신봉2로 5 104호 (신봉동, 에덴파크2)
73. 염광플러스약국/경기도 용인시 수지구 동천로 137 4층 404~406호 (동천동)
74. 예쁜약국/경기도 용인시 수지구 신봉2로 2 센트럴500 223호 (신봉동)
75. 온누리수지약국/경기도 용인시 수지구 문정로 46 (풍덕천동, 한길타운 107호)
76. 우리들약국/경기도 용인시 수지구 현암로 121 201호 (죽전동, 에머랄드그린존 )
77. 우리민들레약국/경기도 용인시 수지구 현암로 132 107호 (죽전동, C.H리베로I)
78. 우리약국/경기도 용인시 수지구 진산로 28 성원상떼빌아파트 상가1동 101호 (상현동)
79. 원약국/경기도 용인시 수지구 성복2로 162 105호 (성복동, LG빌리지6차 상가동)
80. 원희온누리약국/경기도 용인시 수지구 만현로 110 B동 111-2호 (상현동,원희캐슬프라자)
81. 유타워 온누리약국/경기도 용인시 수지구 신수로 767 분당수지 U-TOWER A동 241호 (동천동)
82. 윤진약국/경기도 용인시 수지구 수풍로131번길 2 에덴파크 104호 (동천동)
83. 이화명문약국/경기도 용인시 수지구 현암로 75 101호 (죽전동, 명문약국)
84. 이화약국/경기도 용인시 수지구 성복1로 106 B04호 (성복동)
85. 이화옵티마약국/경기도 용인시 수지구 풍덕천로 119 305호 (풍덕천동, 로얄스포츠센터)
86. 자연약국/경기도 용인시 수지구 만현로 110 원희캐슬프라자 B-304호 (상현동)
87. 자이약국/경기도 용인시 수지구 신봉1로 112-1 109호 (신봉동, LG빌리지5차 단지내 상가)
88. 재일약국/경기도 용인시 수지구 만현로 20 101호 (상현동, 성산빌딩)
89. 정다운온누리약국/경기도 용인시 수지구 현암로 164 103호 (죽전동, 신주프라자)
90. 조이약국/경기도 용인시 수지구 정평로 40-1 거묵상가1 109호 (풍덕천동)
91. 좋은약국/경기도 용인시 수지구 성복2로 51 304호 (성복동,YK타운 비동)
92. 죽전열린약국/경기도 용인시 수지구 용구대로 2702 동춘프라자 1층 (죽전동)
93. 중앙약국/경기도 용인시 수지구 동천로 31 (동천동)
94. 즐거운약국/경기도 용인시 수지구 대지로 43 (죽전동, 금강프라자)
95. 천명약국/경기도 용인시 수지구 동천로 62 (동천동,센트럴상가 108호)
96. 청 한약국/경기도 용인시 수지구 수풍로 95 정원빌딩 1층 (동천동)
97. 청운약국/경기도 용인시 수지구 현암로 127 104호 (죽전동, 신원빌딩)
98. 친절한 해든약국/경기도 용인시 수지구 손곡로 100 111,112호 (동천동, 훼미리프라자)
99. 캐슬프라자약국/경기도 용인시 수지구 만현로 110 (상현동, 원희캐슬프라자A-303A호)
100. 태광약국/경기도 용인시 수지구 성복2로 51 303호 (성복동, 데이파크A동 )
101. 토마토약국/경기도 용인시 수지구 정든로6번길 2 그린피아 303호 (죽전동)
102. 푸른솔약국/경기도 용인시 수지구 광교중앙로 301 (상현동)
103. 푸른온누리약국/경기도 용인시 수지구 풍덕천로 122 (풍덕천동, 103호)
104. 풀향기약국/경기도 용인시 수지구 신봉1로 62 LG프라자 106호 (신봉동)
105. 플러스약국/경기도 용인시 수지구 성복2로 114 (성복동,플러스클리닉수지센타 122호)
106. 필리아약국/경기도 용인시 수지구  대지로 46 103호 (죽전동)
107. 하나약국/경기도 용인시 수지구 수지로296번길 47 107호 (풍덕천동, 수석빌딩)
108. 한가정약국/경기도 용인시 수지구 만현로 110 (상현동, 원희캐슬프라자,A동 106호,203-1호)
109. 한사랑약국/경기도 용인시 수지구 포은대로313번길 4 (풍덕천동, 수지미래빌딩 103호)
110. 행복약국/경기도 용인시 수지구 신봉1로 175 102호 (신봉동, 진성프라자)
111. 행복플러스약국/경기도 용인시 수지구 현암로 131 C.H리베로II 301호 (죽전동)
112. 행복한약국/경기도 용인시 수지구 용구대로 2797 103호 (죽전동, 수창빌딩)
113. 현진약국/경기도 용인시 수지구 만현로 92 116호 (상현동, 아이티프라자)
114. 호수약국/경기도 용인시 수지구 대지로 39 (죽전동, 양지프라자 104호)
115. 희망약국/경기도 용인시 수지구 풍덕천로 119 118호 (풍덕천동, 로얄스포츠센터)

###**예제11-12 서귀포 최저기온 출력**

In [22]:
import csv

f = open('jeju_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)
print(header[1], header[2], header[3])

for line in lines:
  if line[1] == '서귀포' and line[2][5:7] == '01':
    print(line[1], line[2], line[3])

f.close()

지점명 일시 최저기온(°C)
서귀포 2019-01-01 3.8
서귀포 2019-01-02 3.6
서귀포 2019-01-03 2.6
서귀포 2019-01-04 6.6
서귀포 2019-01-05 7.2
서귀포 2019-01-06 7.2
서귀포 2019-01-07 7.6
서귀포 2019-01-08 4.1
서귀포 2019-01-09 4.4
서귀포 2019-01-10 6.7
서귀포 2019-01-11 8.1
서귀포 2019-01-12 7.6
서귀포 2019-01-13 5.9
서귀포 2019-01-14 4.7
서귀포 2019-01-15 5
서귀포 2019-01-16 2.9
서귀포 2019-01-17 2
서귀포 2019-01-18 2.9
서귀포 2019-01-19 5.9
서귀포 2019-01-20 3.5
서귀포 2019-01-21 2.6
서귀포 2019-01-22 3.5
서귀포 2019-01-23 3.1
서귀포 2019-01-24 4.6
서귀포 2019-01-25 3.2
서귀포 2019-01-26 2.2
서귀포 2019-01-27 2.4
서귀포 2019-01-28 5.3
서귀포 2019-01-29 2.8
서귀포 2019-01-30 7.3
서귀포 2019-01-31 4.7

###**예제11-13 서귀포 최저기온 평균**

In [24]:
import csv

f = open('jeju_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

month = 1 # 기준 월
sum = 0
num_day = 0

for line in lines:
  if line[1] == '서귀포' and int(line[2][5:7]) == month:
    sum += float(line[3])
    num_day += 1

avg = sum/num_day

print('%d월 일수 : %d' %(month, num_day))
print('%d월 최저기온 평균 : %.1f' %(month, avg))

f.close()

1월 일수 : 31
1월 최저기온 평균 : 4.6

###**예제11-14 지역별 8월 중 최고기온**

In [25]:
import csv

f = open('jeju_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

month = 8 # 기준 월

max_jeju = -1000
max_sungsan = -1000
max_gosan = -1000
max_suguipo = -1000

for line in lines:
  if line[1] == '제주' and int(line[2][5:7]) == month:
    if float(line[4]) > max_jeju:
      max_jeju = float(line[4])

  if line[1] == '고산' and int(line[2][5:7]) == month:
    if float(line[4]) > max_sungsan:
      max_sungsan = float(line[4])

  if line[1] == '성산' and int(line[2][5:7]) == month:
    if float(line[4]) > max_gosan:
      max_gosan = float(line[4])

  if line[1] == '서귀포' and int(line[2][5:7]) == month:
    if float(line[4]) > max_suguipo:
      max_suguipo = float(line[4])

print("%d월 제주 최고기온 : %.1f" %(month, max_jeju))
print("%d월 고산 최고기온 : %.1f" %(month, max_sungsan))
print("%d월 성산 최고기온 : %.1f" %(month, max_gosan))
print("%d월 서귀포 최고기온 : %.1f" %(month, max_suguipo))

8월 제주 최고기온 : 34.7
8월 고산 최고기온 : 32.9
8월 성산 최고기온 : 32.5
8월 서귀포 최고기온 : 32.2

###**예제11-15 가장 비가 많이 오는 월**

In [27]:
import csv

f = open('jeju_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

sum_rain = [0,0,0,0,0,0,0,0,0,0,0,0]

for line in lines:
  if not line[5]:
    line[5] = 0

  if int(line[2][5:7]) == 1: # 1월 이면
    sum_rain[0] = sum_rain[0] + float(line[5])
  elif int(line[2][5:7]) == 2: # 2월 이면
    sum_rain[1] = sum_rain[1] + float(line[5])
  elif int(line[2][5:7]) == 3: # 3월 이면
    sum_rain[2] = sum_rain[2] + float(line[5])
  elif int(line[2][5:7]) == 4: # 4월 이면
    sum_rain[3] = sum_rain[3] + float(line[5])
  elif int(line[2][5:7]) == 5: # 5월 이면
    sum_rain[4] = sum_rain[4] + float(line[5])
  elif int(line[2][5:7]) == 6: # 7월 이면
    sum_rain[5] = sum_rain[5] + float(line[5])
  elif int(line[2][5:7]) == 7: # 7월 이면
    sum_rain[6] = sum_rain[6] + float(line[5])
  elif int(line[2][5:7]) == 8: # 8월 이면
    sum_rain[7] = sum_rain[7] + float(line[5])
  elif int(line[2][5:7]) == 9: # 9월 이면
    sum_rain[8] = sum_rain[8] + float(line[5])
  elif int(line[2][5:7]) == 10: # 10월 이면
    sum_rain[9] = sum_rain[9] + float(line[5])
  elif int(line[2][5:7]) == 11: # 11월 이면
    sum_rain[10] = sum_rain[10] + float(line[5])
  else: # 12월 이면
    sum_rain[11] = sum_rain[11] + float(line[5])

max_month_rain = max(sum_rain)
max_month = sum_rain.index(max_month_rain) + 1

print("(1) 최대 강수 월과 강수량 : %d월, %.1fmm\n" %(max_month, max_month_rain))
print("(2) 월별 강수량")

for i in range(1, 13):
  print("%d월: %.1fmm" %(i, sum_rain[i-1]))
  
f.close()

(1) 최대 강수 월과 강수량 : 9월, 2018.9mm

(2) 월별 강수량
1월: 79.5mm
2월: 187.1mm
3월: 299.8mm
4월: 296.0mm
5월: 789.4mm
6월: 678.0mm
7월: 1670.0mm
8월: 1258.5mm
9월: 2018.9mm
10월: 700.3mm
11월: 111.1mm
12월: 320.6mm

###**예제11-16 고산 지역 7월 최저/최고 습도**

In [30]:
import csv

f = open('jeju_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

month = 7
min_humidity = 1000
max_humidity = -1000

for line in lines:
  if line[1] == '고산' and int(line[2][5:7]) == month:
    if float(line[6]) < min_humidity:
      min_humidity = float(line[6])

    if float(line[6]) > max_humidity:
      max_humidity = float(line[6])

print("%d월 최저 습도 : %.1f" %(month, min_humidity))
print("%d월 최대 습도 : %.1f" %(month, max_humidity))

f.close()

7월 최저 습도 : 78.5
7월 최대 습도 : 100.0

###**예제11-17 연 강수량 최대 지역 찾기**

In [31]:
import csv

f = open('jeju_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

total_rain = [0,0,0,0]

for line in lines:
  if not line[5]:
    line[5] = 0

  if line[1] == '제주': # '제주' 지역
    total_rain[0] = total_rain[0] + float(line[5]) 

  if line[1] == '고산': # '고산' 지역
    total_rain[1] = total_rain[1] + float(line[5]) 

  if line[1] == '성산': # '성산' 지역
    total_rain[2] = total_rain[2] + float(line[5]) 

  if line[1] == '서귀포': # '서귀포' 지역
    total_rain[3] = total_rain[3] + float(line[5]) 

max_year_rain = max(total_rain)

if total_rain.index(max_year_rain) == 0:
  max_area = '제주'
if total_rain.index(max_year_rain) == 1:
  max_area = '고산'
if total_rain.index(max_year_rain) == 2:
  max_area = '성산'
if total_rain.index(max_year_rain) == 3:
  max_area = '서귀포'

print('(1) 연 강수 최대 지역: %s\n' %max_area)
print('(2) 지역별 강수량')
print('제주: %.1fmm' %total_rain[0])
print('고산: %.1fmm' %total_rain[1])
print('성산: %.1fmm' %total_rain[2])
print('서귀포: %.1fmm' %total_rain[3])

f.close()

(1) 연 강수 최대 지역: 성산

(2) 지역별 강수량
제주: 1979.9mm
고산: 1560.9mm
성산: 2658.1mm
서귀포: 2210.3mm